---
- name: Preparation of the nodes
  ansible.builtin.include_tasks: prepare-nodes.yml
  tags: prepare-nodes

- name: Bootstrap the RKE cluster on the first node
  ansible.builtin.include_tasks: bootstrap-rke.yml
  tags: bootstrap-rke

- name: Joining additional server nodes
  ansible.builtin.include_tasks: join-servers.yml
  tags: join-servers

- name: Joining additional agent nodes
  ansible.builtin.include_tasks: join-agents.yml
  tags: join-agents
