---
- name: Preparation of the nodes
  ansible.builtin.include_tasks: prepare-nodes.yml
  tags: prepare-nodes

- name: Creation of the kube-vip manifest for HA and prepare for loadbalancing
  ansible.builtin.include_tasks: kube-vip.yml
  tags: kube-vip

- name: Bootstrap the RKE cluster on the first node
  ansible.builtin.include_tasks: bootstrap-rke.yml
  tags: bootstrap-rke

# # Adds additional servers using the token from the previous task
# - name: Add additional RKE2 Servers
#   hosts: servers
#   gather_facts: true
#   roles:
#     - add-server

# # Adds agents to the cluster
# - name: Add additional RKE2 Agents
#   hosts: agents
#   gather_facts: true
#   roles:
#     - add-agent

# # Finish kube-vip, add metallb
# - name: Apply manifests after cluster is created
#   hosts: servers
#   gather_facts: true
#   roles:
#     - apply-manifests
