- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true
  become: true

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true
  become: true

- name: Create directory for RKE2 binary
  ansible.builtin.file:
    path: "{{ rke2_installation_install_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Download RKE2 binary
  ansible.builtin.get_url:
    url: "{{ rke2_installation_binary_url }}"
    dest: "{{ rke2_installation_install_dir }}/rke2"
    mode: '0755'
  become: true

- name: Set executable permissions on the RKE2 binary
  ansible.builtin.file:
    path: "{{ rke2_installation_install_dir }}/rke2"
    mode: '0755'
    state: file
  become: true
